### ISSUE TITLE
What is the status of the project

### ISSUE THREAD

**Issue by AlexVPopov** [gavinkflam/bootstrap-social-rails#2]
Hello,

I am interested in contributing to this project, but I don't know how active you are in maintaining it. Can you tell me, if you are interested in contributions. In particular, I would like to add missingvendor assets, such as font awesome.

Cheers,
Alex

**Comment by gavinkflam** [comment]
Nice to meet you Alex. I have just updated the asset to the most recent version 4.12.0.

In my opinion, it would be better to keep this gem simple. Font awesome assets could be obtained from [font-awesome-rails](https://github.com/bokmann/font-awesome-rails) gem.
